name: test-release
on:
  push:
    branches:
    - main
  pull_request:

permissions:
  id-token: write
  contents: read

jobs:
  hello:
    name: say hello
    runs-on: ubuntu-latest
    steps:
      - name: say hello
        uses: iwpnd/github-actions/actions/hello-world@v1.0.0
        with:
          name: Ben

  tag-and-release:
    name: tag-and-release
    runs-on: ubuntu-latest
    env:
      RUNNER_DEBUG: 1
    permissions:
      id-token: write
      contents: write
    if: github.event_name == 'bla' # TODO: re-enable if issue#252 closed
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extends: |
            github:iwpnd/semantic-release-config
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
